### ISSUE TITLE
Rails backtrace lines are relative but start with absolute / 

### ISSUE THREAD

**Issue by jnunemaker** [garrettdimon/minitest-heat#7]
This makes option + clicking the path in vscode terminal not open the file in vscode. 

![Screen Shot 2021-12-09 at 8 37 27 AM](https://user-images.githubusercontent.com/235/145406457-8fac597d-03f6-455b-aebe-d27cd910fa3c.png)

Only seems to happen in rails project. Plain ruby project does the right thing.

**Comment by garrettdimon** [comment]
Can you double check you're running 1.0.0? This was an issue in a previous version for sure, but I'm unable to reproduce it in 1.0.0 in either a plain Ruby or a Rails app.

**Comment by jnunemaker** [comment]
I just checked. Definitely on 1.0 but now I can't recreate. I wonder if it used an old version at first because of spring or something but now is using new. Let's close this out. I'll re-open if I hit it again.
